### ISSUE TITLE
Working with the Web Audio API

### ISSUE THREAD

**Issue by phlco** [johnnypacia/finalproject#1]
Rather than working with the Web Audio API directly, because it's kind of low-level, you might be interested in using a JavaScript library that abstracts away some of those harder spots.

I'd suggest researching a few and see what you come up with.

**Comment by phlco** [comment]
Have you researched getting a user's coordinates via the naviagator object? https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by johnnypacia** [comment]
No, but I'm taking a look at it now! It would be cool to be able to locate a user's coordinates, espeically if I can't get the editing functionality to work. 

In terms of JavaScript libraries, so far I've been looking at howler.js and soundjs. Both seem doable for playback, but not sure about editing yet.

**Comment by johnnypacia** [comment]
I should definitely research using geolocations because I didn't get up to it in either birds assignment. Do you think it needs to be an MVP for this project?
