### ISSUE TITLE
Working with File Uploads and File Manipulation

### ISSUE THREAD

**Issue by phlco** [johnnypacia/finalproject#2]
Have you researched upload and storing audio files?

Have you researched if it's possible to manipulate and write a sound file on the server?

**Comment by phlco** [comment]
You don't want to store your audio files in a SQL database. Have you researched Amazon's s3 for storage?

**Comment by johnnypacia** [comment]
To answer your first question: it looks like uploading/storing audio files is going to cost money even if I use Amazon's s3 storage and it would also require using a more complicated hosting platform than heroku. This and manipulating/writing sound files on the server interests me a lot and it's definitely worth considering for future projects, especially after learning Python. I think it might be beyond the scope for Tuesday though.

**Comment by johnnypacia** [comment]
Instead, I could just store some sound files in my public folder and try to manipulate those using a library like howler.js or pedalboard.js. If I do howler I would use the individual tracks of a song and allow the user to mix the tracks using the multy-sound playback features.  If I do pedalboard.js I'd have a few different kinds of audio tracks and allow users to add sound effects to them.

**Comment by johnnypacia** [comment]
My goal for tonight is to set up a basic app and try implementing each of the libraries to see which would work better. I'm srill considering whether it would be best to do express or ruby/rails

**Comment by johnnypacia** [comment]
Tonight I'm going to build a rails app and test out which library works better. Depending on how that goes I then I'm going to try to set up some basic sass variables that might come in handy.

**Comment by phlco** [comment]
That sounds like a good solution - putting sounds in your public folder.
