### ISSUE TITLE
Tiny Dancer in the house?

### ISSUE THREAD

**Issue by johnnypacia** [johnnypacia/finalproject#4]
Hey Phil, I've searched the internets for tiny dancer/tinydance libraries, api's, audio visualizers and whathaveyou but all I'm seeing is Elton John's tune. Any leads on a link?

**Comment by johnnypacia** [comment]
https://github.com/jsantell/dancer.js

Is this what you were talking about perchance? I can't find the 'tiny' version of it, but looks like it'll make visuals of any audio source so...worth a shot!

**Comment by phlco** [comment]
haha yes i'm sorry it's just dancer. got confused by elton!
