### ISSUE TITLE
setVolume() for Dancer.js

### ISSUE THREAD

**Issue by johnnypacia** [johnnypacia/finalproject#6]
I'm having trouble implementing the followign getter method for setVolume() with Dancer.js. I need to mute the audio file in order to remove the delay that occurs during playback because of buffer time.   

I've looked at the example code on gitHub and the closest I could find was something that looked like this, but I've tried a bunch of things in the console and nothing's pulling the values: 

```
var dancer = new Dancer ();

var a = new Audio();

a.setVolume = function (){
    this.mute;
}
```

I've been using these as references:

https://github.com/jsantell/dancer.js

And this is a working example I found that displays visualizations on the kick of the drum track:

http://codepen.io/jackrugile/pen/iuEcI

**Comment by annarankin** [comment]
Hey Johnny, I'm not at home right now, but I can take at your code if you
give me line numbers, file names, code snippets, and any errors/unexpected
behavior you're getting.

**Comment by johnnypacia** [comment]
Thanks Anna. I just now got the track I was using for dancer.js to sync removing the buffers on my sounds.js file. I have a basic visualizer that displays on the kick drum. 

But I have to learn how to create another visual that's more representative of the track or create separate js files to handle each of the four audio tracks. I was NOT able to do that with the pedalboard library. So, getting effects on all four of the tracks will require using more libraries. I am already using 4 libraries so it's starting to become overwhelming getting everything to sync up properly. If you have advice for how to handle that I'd definitely appreciate it. 

Otherwise, I need to get started with Sass/CSS so I'm going to switch gears and work on that.

**Comment by johnnypacia** [comment]
The more I try to fiddle with the libraries the more it breaks the code that was working previously. I'm started to get pretty discouraged about it. I'm going to try to set up what I can tonight and come in with the most functional app I can create. Will we be able to have pairing sessions tomorrow?

**Comment by annarankin** [comment]
Hey Johnny, I'd avoid adding too many libraries - the more you add, the greater the chances that they won't play nicely together and something will break. We won't be doing pairing tomorrow - we'll be doing the lesson and deployment/any troubleshooting we need to do. I can sit with you for a bit and try to help - I'm still not entirely clear on where you're having your issue/what's not working, though.

Taking a look at your code now.

**Comment by johnnypacia** [comment]
Hey Anna, thanks for offering to help tomorrow. Sorry I haven't sent specific snippets of what isn't working. The code I've pushed up to github all works right now. But my visualizations.js file had code to create a visualizer that worked only for one track, and whenever I used it the mute/unmute buttons on my sounds.js file and the overdrive button on my effects.js file stopped working properly. 

Right now, I'm making some headway with Sass and Rubocop. I'll try to integrate the dancer.js library again tomorrow morning and if I get stuck I will show you exactly where things are going wrong. 

Thanks again for your help! Have a good night.

**Comment by annarankin** [comment]
Hey Johnny, I'm putting together a schedule for sitting with folks - a lot of folks need help today and we're anticipating more with deployment issues, so I'm time-boxing stuff at around fifteen minutes. Please write down a list of specific questions and problems for me so we can maximize the use of this time!
