### ISSUE TITLE
css breaks (a little) when deployed

### ISSUE THREAD

**Issue by johnnypacia** [johnnypacia/finalproject#9]
Howdy Phil, 

The <li> contents on both of my pages are slightly off-centered on my deployed app but perfectly centered locally. Any reasons why that might be happening?

**Comment by johnnypacia** [comment]
<  li >

**Comment by phlco** [comment]
Anna says she fixed it!

**Comment by johnnypacia** [comment]
she totally did! I meant to close this issue, my bad.

thanks for all of your help with this sprint! it's a pleasure working with
you.
